---
title: "Explain the function pre_process_ew_input_carcass_data_flp()"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Explain the function pre_process_ew_input_carcass_data_flp()}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(qp4ewc)
```

# Aim

In this vignette, we will try to build unit tests for the differrent sub-function of `pre_process_ew_input_carcass_data_flp()`. 

# Parameters

The parameters needed are:

```{r, echo = TRUE}
# Sire breed can be: AN,AU,CH,LM,OB,SI corresponding to Angus,Aubrac, Charolais, Limousin, Original-Braunvieh, Simmental
s_sirebreed <- "LM"
# Production system according to ECOWEIGHT: 1,2,3,4 corresponding to purebreeding, crossbreeding, terminal crossing, dairy
s_prodsystew <- "2"
# Marketing channel can be: Natura-Beef, SwissPrimBeef
s_marketingchannel <- "Natura-Beef"
# Path to define from the working directory
s_path_directory2create <- "/Users/skn/muku_Ecoweigth/2022/work"
# Path to input statement for carcass and price
s_input_file_flp_carcass_matrix_statement <- file.path(here::here(),"inst","extdata","ewbc","input_flp_carcass_matrix_statement.txt")
# Path to flp data file
s_input_file_flp <- file.path(here::here(),"inst","extdata","ewbc","test","test_zws_muku_flp.csv")
# Date YYYYMMDD used as start date to filter data for calving or carcass
s_start_flp_date <- 20050101
# Date YYYYMMDD used as end date to filter data for calving or carcass
s_end_flp_date <- 20211231
# Path to input with cow price. Based on this example an other file can be created with different input-values.
s_input_file_price_cow <- file.path(here::here(),"inst","extdata","ewbc","cow_price.txt")
# Path to input with bull price. Based on this example an other file can be created with different input-values.
s_input_file_price_bull <- file.path(here::here(),"inst","extdata","ewbc","bull_price.txt")
# Path to input with heifer price. Based on this example an other file can be created with different input-values.
s_input_file_price_heifer <- file.path(here::here(),"inst","extdata","ewbc","heifer_price.txt")
# Flag to set to TRUE, if a log-file is whished
b_log <- TRUE
```


```{r, warning=FALSE, message=FALSE}
tbl_flp <- read_file_input_flp(ps_input_file_flp = s_input_file_flp,
                               ps_start_flp_date = s_start_flp_date,
                               ps_end_flp_date = s_end_flp_date,
                               ps_sirebreed = s_sirebreed,
                               pb_log = b_log)
```


# Frequency per slaughtercategory

```{r}
# Frequency of the cows are not depending of a marketing channel
freq_mat_cow <- build_freq_conf_fat(ps_input_flp_tibble = tbl_flp,
                                    ps_sex = "F",
                                    ps_marketing_channel = NULL,
                                    ps_flag_cow = TRUE,
                                    pb_log = b_log)
freq_mat_cow
```

```{r}
s_output_matrix_freqmatcow <- file.path(here::here(),"inst","extdata","ewbc","test","test_mat_freqmat_cow.csv")
#write.table(freq_mat_cow, s_output_matrix_freqmatcow, col.names = NA)

tbl_freq_mat_cow <- readr::read_delim(file = s_output_matrix_freqmatcow, delim = " ", col_names = FALSE)
tbl_freq_mat_cow <- tbl_freq_mat_cow %>% dplyr::select(-c(1))
tbl_freq_mat_cow <- tbl_freq_mat_cow[-1,]
input_freq_mat_cow <- matrix(as.numeric(as.matrix(tbl_freq_mat_cow)), ncol = ncol(tbl_freq_mat_cow))
```

## Price coefficient for cow

```{r}
s_output_matrix_cowprice <- file.path(here::here(),"inst","extdata","ewbc","test","test_mat_coeffprice_cow.csv")
# Price table with combination of carcass fat and conformation for Natura-cows
mat_coeffprice_cow <- read_price_conf_fat(ps_input_file_price = s_input_file_price_cow,
                                          pb_log = b_log)
#write.table(mat_coeffprice_cow, s_output_matrix_cowprice, col.names = NA)
```
```{r}
tbl_coeffprice_cow <- readr::read_delim(file = s_output_matrix_cowprice, delim = " ", col_names = FALSE)
tbl_coeffprice_cow <- tbl_coeffprice_cow %>% dplyr::select(-c(1))
tbl_coeffprice_cow <- tbl_coeffprice_cow[-1,]
input_mat_coeffprice_cow <- matrix(as.numeric(as.matrix(tbl_coeffprice_cow)), ncol = ncol(tbl_coeffprice_cow))
```

