---
title: "Results_and_pie_charts_developping"
author: "Sophie Kunz"
date: "5/20/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup}
library(qp4ewc)
```

# Developing post_process_ewbc_output()

```{r}
s_path_2outputfile <- "/Users/skn/muku_Ecoweigth/2022/work/price_trial_10_08"
s_output_file <- file.path(here::here(),"inst","extdata","ewbc","output_statement.txt")
s_output_search_pattern <- file.path(here::here(),"inst","extdata","ewbc","output_searchpattern.txt")
b_log <- TRUE

```

```{r, warning=FALSE, message=FALSE}
tbl_aggregate_results <- post_process_ewbc_output(ps_path_2outputfile = s_path_2outputfile,
                                                  ps_output_statement = s_output_file,
                                                  ps_output_search_pattern = s_output_search_pattern,
                                                  pb_log = b_log,
                                                  plogger = NULL)
```


# Developing plot_piechart_ewbc()

```{r}
s_path_2genSD <- file.path(here::here(),"inst","extdata","ewbc","input_geneticSD.txt") 
s_traitgroup2consider <- "Functional Traits"
s_sirebreed <- "LM"
s_prodsystew <- "2"
s_marketchannel <- "Natura-Beef"
```

```{r}
library(ggplot2)
library(forcats)
```


```{r}
plot_piechart_ewbc(ps_path_2genSD = s_path_2genSD,
                   ptbl_aggregate_results = tbl_aggregate_results,
                   ps_traitgroup2consider = s_traitgroup2consider,
                   ps_sirebreed = s_sirebreed,
                   ps_prodsystew = s_prodsystew,
                   ps_marketchannel = s_marketchannel,
                   pb_log = b_log,
                   plogger = NULL)
```
The post-processing functions has been developed based on the internship analysis.
These need to be updated for the different scenario, traits, etc.
